### ISSUE TITLE
How to test APIs locally with xsuaa properties

### ISSUE THREAD

**Issue by JerryZhang0929** [SAP/cloud-security-xsuaa-integration#1043]
I am following the link below to set up the configuration and do local testing. If  I deploy the app to BTP and bind xsuaa service instance, I can get access token  with oauth authorize, token url, client id and secret and test my REST APIs. 

But I have no idea about how to get JWT and call my API locally. The uaadomain and url for xsuaa service is localhost. Then what is the oauth token url and authorize url? Is it "http://localhost:8080/oauth/authorize"?

[https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-security#local-setup-fails-with-application-failed-to-start ](url)

Application yaml configuration
```
sap:
  security:
    services:
      xsuaa:
        xsappname: bt001e00_purchase-order-xsuaa!t26007
        uaadomain: host
        #uaadomain: authentication.eu10.hana.ondemand.com
        clientid: sb-bt001e00_purchase-order-xsuaa!t26007
        clientsecret: QkJEpdLjRTv85HXZK/qem82oQp0=
        #url: https://XXX.authentication.eu10.hana.ondemand.com
        url: http://localhost
```
