### ISSUE TITLE
How to set proxy for local testing

### ISSUE THREAD

**Issue by JerryZhang0929** [SAP/cloud-security-xsuaa-integration#1049]
The local testing is very helpful. It works fine if I configure the the parameters from remote xsuaa service instance and test outside of corporate network. But if I am working behind a corporate firewall, it always told me "Error retrieving Json Web Keys from Identity Service: Error retrieving token keys: No such host is known ([subdomain].authentication.eu10.hana.ondemand.com)." It is a proxy issue. 

Is supported to set the proxy when it is going to retrieve Json Web Keys from cloud service?

Configuration in application.yml
```
sap:
  security:
    services:
      xsuaa:
        xsappname: bt001e00_purchase-order-xsuaa!t26007
        #uaadomain: host
        uaadomain: authentication.eu10.hana.ondemand.com
        clientid: [client id]
        clientsecret: [client secret]
        url: https://[subdomain].authentication.eu10.hana.ondemand.com
```
