### ISSUE TITLE
App is not starting on cloud foundry without dummy values for services.identity

### ISSUE THREAD

**Issue by adamandre79** [SAP/cloud-security-xsuaa-integration#790]
Hello colleagues,

I have added all the dependencies mentioned here: https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/spring-security/README.md

But did not get the application running in cloud foundry, I also tried different combinations  of the properties `sap.spring.security.hybrid.auto` and `sap.spring.security.xsuaa.flows.auto`. Because our application is only bound against csuaa I set the parameters like:

`sap.spring.security.hybrid.auto: true`
`sap.spring.security.xsuaa.flows.auto: false`

But with or without the parameters I always got an error message during startup. Without the parameters set I got a error that client ID is missing, with the parameters set, that some configuration class could not be found.

Only if I set the following properties in my application.yaml it works:

```
sap.security.services.identity:
  clientid:  irrelevant
  domains:
    - doesntmatter
```

The missing client Id did not come from the xsuaa instance, there a client Id was found, but from the IAS service configuration which was not found.
It took me several hours to find this solution and the questions are now:

1. Is there a better way without the properteies for `sap.security.services.identity` to get the application running only with binding to xsuaa?
2. If not, could you include a better way for the future?

Regards
André

**Question Summary**
If applicable, please mention:
- client library: java-security:2.11.11
- Environment: Cloud Foundry

**Comment by liga-oz** [comment]
Hi @adamandre79,

the spring-security module is aimed at identity service combined with xsuaa or cloud authorization(in future) service usage. It is not meant to be used for a xsuaa only. If you want to use only xsuaa service I would suggest to use [spring-xsuaa](https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-xsuaa) instead.

Kind Regards,
Liga

**Comment by nenaraab** [comment]
Hi @adamandre79 

Have you tried with
```
sap:
  security:
    services:
      xsuaa:
        xsappname: xsapp!t0815
        uaadomain: localhost
        clientid: sb-clientId!t0815
        clientsecret: pwd
        url: http://localhost
```

#### Further references:
- https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/spring-security/Migration_SpringXsuaaProjects.md

**Comment by adamandre79** [comment]
Hello @nenaraab ,

I tried with this, but without the following it was not working:
```
      identity:
        clientid: sb-clientId!t0815
        domain: localhost
        url: http://localhost
```
But in addition we can't add this in our application.yaml, because the app name and client id and secret will change in different spaces. 

Regards
André

**Comment by nenaraab** [comment]
Hi @adamandre79 you tried with `... identity` but i suggested with `xsuaa` 👍

**Comment by adamandre79** [comment]
Hello @nenaraab ,

I tried for Spring Boot tests with `xsuaa` only in the application.yaml, this was not working and I had to add the `identity` information in addition, only with both it was woking.

Also for information from VCAP_SERVICES it was not working without adding `identity` dummy information in application.yaml.

I checked the coding from the java security library and found in class `HybridIdentityServicesAutoConfiguration` the method:

```
public JwtDecoder hybridJwtDecoder(XsuaaServiceConfiguration xsuaaConfig,
				IdentityServiceConfiguration identityConfig)
```

tries to create a `JwtDecoder` with `XSUAA` and `IAS`. Because there are no `identity` information in the environment I got the error:

```
java.lang.IllegalStateException: Failed to load ApplicationContext
Failed to instantiate [org.springframework.security.oauth2.jwt.JwtDecoder]: Factory method 'hybridJwtDecoder' threw exception; nested exception is java.lang.IllegalArgumentException: JwtAudienceValidator requires a clientId.
```

The error comes up with properties in application.yaml:
```
sap:
  security:
    services:
      xsuaa:
        xsappname: test-srv
        uaadomain: localhost
        clientid: test-srv!t0815
        url: http://localhost:1111
```

If I add the identity part it works:
```
sap:
  security:
    services:
      identity:
        clientid: test-srv!t0815
        domains:
          - localhost
      xsuaa:
        xsappname: test-srv
        uaadomain: localhost
        clientid: test-srv!t0815
        url: http://localhost:1111
```


Unfortunately I can't share our project because it is productive coding from SAP SE which can't be shared here.

I hope this helps.

Regards
André
